server {
    listen 80 default_server;
    root /var/www/html/public;
    index index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location /up {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
